# superset/Dockerfile
FROM apache/superset:4.1.1

USER root

# Install DuckDB SQLAlchemy driver + dependencies
RUN pip install --no-cache-dir \
    trino==0.337.0\
    sqlalchemy-trino==0.5.0 \
    sqlalchemy==1.4.54 \
    psycopg2-binary

USER superset