#Get latest image of dbt
FROM ghcr.io/dbt-labs/dbt-core:latest 

#Install the duckdb adapter and duckdb
RUN pip install --no-cache-dir --break-system-packages \
    "numpy<2" \
    dbt-duckdb==1.10.1 \
    duckdb==1.4.4 \
    deltalake==0.17.0 \
    "pyarrow==14.0.0" \
    boto3==1.34.0
