#Get latest image of dbt
FROM python:3.11-slim

#Needed for packages install
RUN apt-get update && apt-get install -y \
    gcc \
    g++ \
    curl \
    git \
    && rm -rf /var/lib/apt/lists/*

#Install the duckdb adapter and duckdb
RUN pip install --no-cache-dir  \
    "numpy<2" \
    dbt-duckdb==1.10.1 \
    duckdb==1.4.4 \
    deltalake==0.17.0 \
    pyarrow==23.0.0 \
    boto3==1.34.0 \
    fastapi>=0.110.0 \
    uvicorn>=0.29.0 \
    pydantic>=2.0.0

WORKDIR /usr/app/dbt