name: multi_domain_lakehouse
version: "1.0.0"
config-version: 2

profile: multi_domain_lakehouse

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]

clean-targets: ["/tmp/dbt_target"]

models:
  multi_domain_lakehouse:
    staging:
      +materialized: view
      taxi:
        +tags: ["taxi", "staging"]
      weather:
        +tags: ["weather", "staging"]

    intermediate:
      +materialized: view
      taxi:
        +tags: ["taxi", "intermediate"]
      weather:
        +tags: ["weather", "intermediate"]

    gold:
      +materialized: external
      +format: parquet
      taxi:
        +location_root: "s3://artifacts/dbt/taxi/staging"
        +tags: ["taxi", "gold"]
      weather:
        +location_root: "s3://artifacts/dbt/weather/staging"
        +tags: ["weather", "gold"]

seeds:
  multi_domain_lakehouse:
    +schema: seeds
