name: multi_domain_lakehouse
version: "1.0.0"
config-version: 2

profile: multi_domain_lakehouse

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]

#This is done so airflow can reach this in docker
clean-targets: ["/tmp/dbt_target"]

models:
  multi_domain_lakehouse:
    staging:
      +materialized: view
      taxi:
        +tags: ["taxi", "staging"]
      github_archive:
        +tags: ["github", "staging"]
      retail:
        +tags: ["retail", "staging"]
      weather:
        +tags: ["weather", "staging"]

    intermediate:
      +materialized: view
      taxi:
        +tags: ["taxi", "intermediate"]
      github_archive:
        +tags: ["github", "intermediate"]
      retail:
        +tags: ["retail", "intermediate"]
      weather:
        +tags: ["weather", "intermediate"]

    gold:
      +materialized: external
      +format: parquet
      taxi:
        +location_root: "s3://artifacts/dbt/taxi/staging"
        +tags: ["taxi", "gold"]
      github_archive:
        +location_root: "s3://artifacts/dbt/github_archive/staging"
        +tags: ["github", "gold"]
      retail:
        +location_root: "s3://artifacts/dbt/retail/staging"
        +tags: ["retail", "gold"]
      weather:
        +location_root: "s3://artifacts/dbt/weather/staging"
        +tags: ["weather", "gold"]

seeds:
  multi_domain_lakehouse:
    +schema: seeds
